window.DEFAULT_CATALOG_SECTIONS = [
  {
    id: 'ajuar',
    kicker: 'Ajuar y esenciales',
    title: 'Esenciales delicados para los primeros días.',
    description: 'Una selección suave y amorosa para armar el ajuar con calma.',
    helper: 'Consultanos si querés ver más fotitos o armar un set.',
    items: [
      { label: 'Ajuar', title: 'Ajuar clásico', images: ['ajuar.jpg', 'ajuar1.jpg'] },
      { label: 'Ajuar', title: 'Ajuar de 3 piezas', images: ['ajuar3piezas.jpg'] },
      { label: 'Esencial', title: 'Kit bebé', images: ['kitbebe.jpg', 'kitbebe1.jpg', 'kitbebe2.jpg'] },
      { label: 'Textil', title: 'Manta de algodón', images: ['mantasdealgodon.jpg'] },
      { label: 'Textil', title: 'Trapitos suaves', images: ['trapitosbebe.jpg'] },
      { label: 'Esencial', title: 'Pañal de tela', images: ['pañaldetela.jpg'] },
      { label: 'Básico', title: 'Ranitas suaves', images: ['ranitas.jpg'] },
    ],
  },
  {
    id: 'ropa',
    kicker: 'Ropita y conjuntos',
    title: 'Ropita pensada para vestir cada momento con ternura.',
    description: 'Vestidos, conjuntos, abrigos y básicos presentados de forma más linda y ordenada.',
    helper: 'Consultanos por talle, colores o disponibilidad.',
    items: [
      { label: 'Abrigo', title: 'Abrigo de hilo', images: ['abrigodehilotalleunico.jpg'] },
      {
        label: 'Abrigo',
        title: 'Abrigo de morley con lanilla',
        images: [
          'abrigodemorleyconlanilla.jpg',
          'abrigodemorleyconlanilla1.jpg',
          'abrigodemorleyconlanilla2.jpg',
          'abrigodemorleyconlanilla3.jpg',
          'abrigodemorleyconlanilla4.jpg',
        ],
      },
      { label: 'Abrigo', title: 'Abrigo de plush', images: ['abrigodeplushtalle5.jpg'] },
      { label: 'Básico', title: 'Body manga larga', images: ['bodymangalargatalle6.jpg'] },
      { label: 'Camisa', title: 'Camisita blanca', images: ['camisablancatalle3.jpg'] },
      { label: 'Conjunto', title: 'Conjunto azul', images: ['conjuntoazultalle2.jpg'] },
      { label: 'Conjunto', title: 'Conjunto de algodón', images: ['conjuntodealgodon.jpg', 'conjuntodealgodon1.jpg'] },
      { label: 'Conjunto', title: 'Conjunto de plush', images: ['conjuntodeplush.jpg'] },
      { label: 'Conjunto', title: 'Conjunto de lino', images: ['Conjuntosdelinotalle4.jpg', 'Conjuntosdelinotalle4v2.jpg'] },
      { label: 'Conjunto', title: 'Conjunto delicado', images: ['conjuntotalle1.jpg', 'conjuntotalle1v2.jpg'] },
      { label: 'Enterito', title: 'Enterito peludito', images: ['enteritopeluditoconbroche.jpg'] },
      { label: 'Bebé', title: 'Jardinero', images: ['jardinero.jpg', 'jardinero1.jpg'] },
      { label: 'Básico', title: 'Palazo de plush', images: ['Únicopalazodeplushtalle5.jpg'] },
      {
        label: 'Pantalón',
        title: 'Pantalones de algodón',
        images: [
          'pantalonesdealgodon.jpg',
          'pantalonesdealgodon1.jpg',
          'pantalonesdealgodon2.jpg',
          'pantalonesdealgodon3.jpg',
        ],
      },
      { label: 'Pijama', title: 'Pijama Poplar', images: ['pijamapoplar.jpg'] },
      { label: 'Pijama', title: 'Pijamas suaves', images: ['pijamas.jpg', 'pijamas1.jpg'] },
      { label: 'Pijama', title: 'Pijamas de algodón', images: ['pijamasdealgodon.jpg', 'pijamasdealgodon1.jpg'] },
      { label: 'Básico', title: 'Remerita suave', images: ['remeritatalle2.jpg'] },
      {
        label: 'Vestido',
        title: 'Vestido de corderoy',
        images: ['vestidodecorderoy.jpg', 'vestidodecorderoy1.jpg', 'vestidodecorderoy2.jpg', 'vestidodecorderoy3.jpg'],
      },
      {
        label: 'Vestido',
        title: 'Vestido de morley con vincha',
        images: ['vestidodemorleyconvincha.jpg', 'vestidodemorleyconvincha1.jpg', 'vestidodemorleyconvincha2.jpg'],
      },
      {
        label: 'Vestido',
        title: 'Vestido waffle',
        images: ['vestidodewafleknit.jpg', 'vestidodewafleknit1.jpg', 'vestidodewafleknit2.jpg'],
      },
      { label: 'Vestido', title: 'Vestido para nena', images: ['vestidonena.jpg', 'vestidonena1.jpg'] },
    ],
  },
  {
    id: 'accesorios',
    kicker: 'Accesorios y detalles',
    title: 'Detalles tiernos para completar cada compra.',
    description: 'Accesorios elegidos para sumar practicidad y un toque dulce al catálogo.',
    helper: 'Consultanos por colores, modelos o disponibilidad.',
    items: [
      { label: 'Accesorio', title: 'Chupete y portachupete', images: ['chpete y portachupete.jpg'] },
      { label: 'Accesorio', title: 'Chupete frutal', images: ['chupetefurta.jpg', 'chupetefrutav2.jpg'] },
      { label: 'Mamadera', title: 'Mamadera 260 ml', images: ['mamadera260ml.jpg', 'mamaderde260ml2.jpg'] },
      { label: 'Mamadera', title: 'Mamadera de silicona', images: ['mamaderadesilicona.jpg'] },
      { label: 'Repuesto', title: 'Repuesto para mamadera Philips', images: ['repuestomamaderaphilips.jpg'] },
      { label: 'Accesorio', title: 'Medias para bebé', images: ['mediasbebes.jpg'] },
      { label: 'Accesorio', title: 'Turbante', images: ['turbante.jpg'] },
      { label: 'Accesorio', title: 'Vincha de morley', images: ['vinchademorley.jpg'] },
      { label: 'Accesorio', title: 'Vinchas de plush', images: ['vinchasdeplush.jpg'] },
    ],
  },
];
